# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'ROS2 par la pratique'
copyright = '2025, Manuel YGUEL'
author = 'Manuel YGUEL'
release = '1.0.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.graphviz",
    "sphinx.ext.ifconfig",
    "sphinx.ext.intersphinx",
    "sphinx_copybutton",
    "sphinx_tabs.tabs",
    "sphinx_rtd_theme",
    "myst_parser",
    "sphinx_design",
    "sphinxcontrib.bibtex",
]

myst_enable_extensions = ["colon_fence"]

numfig = True # Enable figure, table, code blocks numbering

# Optional: Customize the labels for different object types
numfig_format = {
    'figure': 'Figure %s',
    'table': 'Tableau %s',
    'code-block': 'Listing %s',
    'download': 'Download %s',
    'section': 'Section %s',
}

bibtex_bibfiles = ['c99_appendix/references.bib']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
#language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
source_suffix = [".rst", ".md"]

# List of directives that are to be inserted into the content body
# 1. underline. Usage: :underline:`text to underline`
# 2. add a line break. Usage: text ends with a line break |br|
rst_prolog = """
.. role:: underline
    :class: underline

.. |br| raw:: html

      <br>
"""

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

html_sidebars = {
    '**': [
        'globaltoc.html',   # Use the global TOC instead of the local one
        'relations.html',   # Adds links to the previous and next chapters
        'searchbox.html',   # Adds a search box
    ]
}

html_theme_options = {
    'language_selector': True,
    'flyout_display': 'always',
}

# -- Options for copybutton extension ----------------------------------------
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True


# -- Options for internationalization ---------------------------------------
locale_dirs = ['locales']
gettext_compact = False  # Ensure separate folders for each language

# Tell Sphinx to look for e.g. slide002_tree_graph.en.png or slide002_tree_graph.fr.png
figure_language_filename = '{root}.{language}{ext}'

import sphinx,os
from pathlib import Path

html_context = {
  'current_version' : "humble",
  'current_language' : None,
  'current_language_code' : None,
  'versions' : [
      ["humble", None], 
      #["jazzy", None]
    ],
  'languages': [
      ["en", "en"], 
      ["fr", "fr"]
    ]
}

LANG_MAP = {
    'en': 'en',
    'fr': 'fr'
}

base_uri = None

def on_builder_inited(app):
    global base_uri
    outdir = Path(app.outdir)

    if None == base_uri:
        base_uri = outdir.parent.parent
    app.config.html_context['base_url'] = base_uri
    print(f"Base URL set to: {base_uri}")

def on_config_inited(app, config):
    global base_uri
    print(f"Language set to: {config.language}")
    if "" != config.html_baseurl:
        base_uri = "https://"+config.html_baseurl
        print(f"Base URL set to: {base_uri}")
    else:
        print(f"Base URL not set")

    # Also store the current language that Sphinx is building:
    if config.language is not None:
        config.html_context['current_language'] = config.language
        config.html_context['current_language_code'] = LANG_MAP[config.language]

def setup(app):
    app.connect('config-inited', on_config_inited)
    app.connect('builder-inited', on_builder_inited)


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = [
    "css/custom.css",
]