name: Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ humble ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            sudo apt-get update -qq
            sudo apt-get install -y -qq python3-sphinx
            cd ./doc/sphinx/
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
      - name: Build documentation
        run: |
            cd ./doc/sphinx/
            source .venv/bin/activate
            mkdir -p build/html/humble/fr/_static
            mkdir -p build/html/humble/en/_static
            cp source/logo.svg build/html/humble/fr/_static/logo.svg
            cp source/locales/logo.en.svg build/html/humble/en/_static/logo.svg
            make gettext
            sphinx-build -b gettext source build/gettext
            sphinx-build -b html -D language=fr -D html_baseurl="yguel.github.io/ros2_in_practice" ./source ./build/html/humble/fr
            sphinx-build -b html -D language=en -D html_baseurl="yguel.github.io/ros2_in_practice" ./source ./build/html/humble/en
            cd ../..
      - name: Create commit
        run: |
            git clone https://github.com/yguel/ros2_in_practice.git --branch gh-pages --single-branch gh-pages
            mkdir -p gh-pages
            cp -r ./doc/sphinx/build/html/* gh-pages/
            cd gh-pages
            rm -f index.html
            cat <<EOF > index.html
            <!DOCTYPE html>
            <html>
            <head>
                <meta http-equiv="refresh" content="0; url=humble/en/index.html">
                <link rel="canonical" href="https://yguel.github.io/ros2_in_practice/humble/en/index.html">
            </head>
            <body>
                <p>If you are not redirected, <a href="humble/en/index.html">click here</a>.</p>
            </body>
            </html>
            EOF
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            touch .nojekyll
            git add .
            git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}